:collections:
  :red_hat_cloud_service_providers:
    :description: Red Hat Cloud Service Providers
    :identifier: redhat_cloud_service
    :options:
    - :collection
    :verbs:
    - :get
    - :post
    :klass: ExtManagementSystem
    :collection_actions:
      :get:
      - :name: read
        :identifier: redhat_cloud_services
      :post:
      - :name: sync
        :identifier: redhat_cloud_services
    :resource_actions:
      :get:
      - :name: read
        :identifier: redhat_cloud_services
      :post:
      - :name: sync
        :identifier: redhat_cloud_services
